name: BlueSky Release Post

on:
  push:
    tags:
      - 'v*' # This means: "Run this whenever I push a tag starting with 'v'"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Post to BlueSky
        uses: myConsciousness/bluesky-post@v5
        with:
          # Improved Copy
          text: |
            🚀 [@tenorlab/vue-dashboard](https://www.npmjs.com/package/@tenorlab/vue-dashboard) ${{ github.ref_name }} is now live on NPM.
            
            ✨ Demo: https://vue.tenorlab.com

            #vue #dashboards #typescript
            
          identifier: ${{ secrets.BSKY_HANDLE }}
          password: ${{ secrets.BSKY_PASSWORD }}
          
          # IMAGE OPTION: 
          # To use this, ensure the file exists in your repo.
          # image: ./assets/banner.png